server.port=${PORT:8081}
  spring.datasource.url=jdbc:mysql://localhost:3308/springdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/interactions
gemini.api.model=gemini-3.6-flash